context:
  version: "0.0.16"
  python_min: 3.10

package:
  name: gepa
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/gepa/gepa-${{ version }}.tar.gz
    sha256: 4390d6061653d321daf4955610ad640471c8cbe193d8ad251907e9b794adffff

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.1
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - gepa
      pip_check: true

about:
  homepage: https://github.com/gepa-ai/gepa
  summary: A framework for optimizing textual system components (AI prompts, code snippets, etc.) using LLM-based reflection and Pareto-efficient evolutionary search.
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - moritzwilksch
